export const COMPONENT_IDS = {
  LIST_STUFF_EDIT: 'list-stuff-edit',
  NAVBAR_ADD_STUFF: 'navbar-add-stuff',
  NAVBAR_LIST_STUFF: 'navbar-list-stuff',
  NAVBAR_ROOM_LIST: 'navbar-room-list',
  NAVBAR_LIST_STUFF_ADMIN: 'navbar-list-stuff-admin',
  NAVBAR_STUDENT_REQUESTS: 'navbar-student-requests',
  NAVBAR_FACULTY_REQUESTS: 'navbar-faculty-requests',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_FACULTY_INFORMATION: 'navbar-faculty-information',
  NAVBAR_CLUB_INFORMATION: 'navbar-club-information',
  NAVBAR_ADMIN_RESERVATION: 'navbar-admin-reservation',
  NAVBAR_ADMIN_MANAGE: 'navbar-admin-manage',
  NAVBAR_COLLAPSE: 'navbar-collapse',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_MANAGE_DROPDOWN: 'navbar-manage-dropdown',
  NAVBAR_MANAGE_DROPDOWN_DATABASE: 'navbar-manage-dropdown-database',
  NAVBAR_PROFILE: 'navbar-profile',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_FIRST_NAME: 'sign-up-form-first-name',
  SIGN_UP_FORM_LAST_NAME: 'sign-up-form-last-name',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_IMAGE: 'sign-up-form-image',
  SIGN_UP_FORM_POSITION: 'sign-up-form-position',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',
  FACULTY_INFORMATION_SORT: 'faculty-information-sort',
  FACULTY_INFORMATION_SEARCH: 'faculty-information-search',
  CLUB_INFORMATION_SEARCH: 'club-information-search',
  ADMIN_MANAGE: 'admin-manage',
  ADMIN_RESERVATION: 'admin-reservation',

  // EDIT PROFILE
  EDIT_PROFILE_FORM_FIRST_NAME: 'edit-profile-form-first-name',
  EDIT_PROFILE_FORM_LAST_NAME: 'edit-profile-form-last-name',
  EDIT_PROFILE_FORM_PFP: 'edit-profile-form-pfp',
  EDIT_PROFILE_FIRST_NAME_ADMIN: 'edit-profile-first-name-admin',
  EDIT_PROFILE_LAST_NAME_ADMIN: 'edit-profile-last-name-admin',
  EDIT_PROFILE_POSITION_ADMIN: 'edit-profile-position-admin',

  // EDIT ROOM
  EDIT_ROOM_NUMBER_ADMIN: 'edit-room-number-admin',
  EDIT_ROOM_TYPE_ADMIN: 'edit-room-type-admin',
  EDIT_ROOM_CAPACITY_ADMIN: 'edit-room-capacity-admin',
  EDIT_BUILDING_ADMIN: 'edit-building-admin',
  EDIT_ROOM_OCCUPANTS_ADMIN: 'edit-room-occupants-admin',
  EDIT_ROOM_SQFT_ADMIN: 'edit-room-sqft-admin',
  EDIT_ROOM_ISICS_ADMIN: 'edit-room-isics-admin',

  // ADD ROOM
  ADD_ROOM_NUMBER_ADMIN: 'add-room-number-admin',
  ADD_ROOM_TYPE_ADMIN: 'add-room-type-admin',
  ADD_ROOM_CAPACITY_ADMIN: 'add-room-capacity-admin',

};
